name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: gbxyz/rdapper:latest
    steps:
      - uses: actions/checkout@v4
      - run: perl Makefile.PL
      - run: make test
